### ISSUE TITLE
Hi,alexgarbarev,(Forgive me is a novice)Could you give a demo so that i understand your project?

### ISSUE THREAD

**Issue by feng-tianyou** [appsquickly/TyphoonRestClient#11]
thanks

**Comment by alexgarbarev** [comment]
Hey @DaisukeZJY. I think you can start from this guide: https://github.com/appsquickly/TyphoonRestClient/wiki/Quick-Start

**Comment by alexgarbarev** [comment]
Feel free to ask any questions
